# Generated by Django 2.0.3 on 2018-04-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
